version: '3'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - 3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network-name
    command: npm run start

  serviceone:
    build: ./services/service-1
    container_name: serviceone
    environment:
      - PORT=4000
    ports:
      - 4000
    volumes:
      - ./services/service-1:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network-name
    command: npm run start

  servicetwo:
    build: ./services/service-2
    container_name: servicetwo
    environment:
      - PORT=5000
    ports:
      - 5000
    volumes:
      - ./services/service-2:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network-name
    command: npm run start

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ENV=development
      - APPLICATION_URL=http://ismydependencysafe
    ports:
      - 3000:3000
      - 443:443
    networks:
      - my-network-name

networks:
  my-network-name:
